image:
  file: .gitpod.Dockerfile

tasks:
  - init: composer create-project laravel/laravel example-app &&  sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env && sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env

